### ISSUE TITLE
we are on the good path

### ISSUE THREAD

**Issue by TucudeanAdrian** [FieldRobotEvent/Virtual_Field_Robot_Event#22] opened 2021-05-16 17:11 UTC
after we builded the program , before running u need to add **source devel/setup.bash** so the terminal recognize the workspace

also when starting simulator i had less errors than before and these are the one that remained

[urdf_spawner-9] process has died [pid 24187, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -model jackal -param robot_description -x 4.455963 -y -5.420603 -z 0.700000 -R 0 -P 0 -Y 1.616329 __name:=urdf_spawner __log:=/home/tucudean/.ros/log/b69a4a3a-b668-11eb-9675-9408536fe0d9/urdf_spawner-9.log].
log file: /home/tucudean/.ros/log/b69a4a3a-b668-11eb-9675-9408536fe0d9/urdf_spawner-9*.log
[Err] [Node.cc:105] No namespace found

i have Ubuntu 18 as OS on my laptop and probably these things happens cuz im not in root like in VM

**Comment by TucudeanAdrian** [comment] 2021-05-16 17:17
i have linux distro and probably these things happens cuz im not in root like in VM

**Comment by ThijsRuigrok** [comment] 2021-05-19 10:30
Sorry for the late response. I do not think you need to be root to run the script. Did you start with a clean version of ubuntu? The error message is not very descriptive, can you supply the ros log files, mentioned in the error message?

**Comment by Darkproduct** [comment] 2021-05-19 14:03
Yes. You always need to source the used ROS version `source /opt/ros/<version>/setup.bash` and your WS `source ws/devel/setup.bash`. This is important. Without sourcing your WS, ROS doesn't find the packages in your WS. This is especially important for this package here, to enable gazebo to find all the models. This is done, with the export in the package.xml. Therefore you need to build your WS at least once and source the setup.bash.

**Comment by ThijsRuigrok** [comment] 2021-05-26 09:12
I assume that the problem is solved and will therefore close the issue. If there is still a problem you can reopen this issue.

**Closed by ThijsRuigrok** 2021-05-26 09:12 UTC
